apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: weave-net
spec:
  template:
    metadata:
      labels:
        name: weave-net
    spec:
      hostNetwork: true
      containers:
        - name: weave
          image: weaveworks/weave-kube:1.6.1-beta
          imagePullPolicy: Always
          command:
            - /home/weave/launch.sh
          env:
            - name: WEAVE_VERSION
              value: 1.6.1-beta
            - name: IPALLOC_RANGE
              value: 10.244.0.0/14
          securityContext:
            privileged: true
          volumeMounts:
            - name: weavedb
              mountPath: /weavedb
            - name: cni-bin
              mountPath: /opt/cni/bin
            - name: cni-conf
              mountPath: /etc/cni/net.d
          securityContext:
            privileged: true
      restartPolicy: Always
      volumes:
        - name: weavedb
          emptyDir: {}
        - name: cni-bin
          hostPath:
            path: /opt/cni/bin
        - name: cni-conf
          hostPath:
            path: /etc/cni/net.d
